### PR TITLE
feat(parser): recognize Jira blocks

### PR DESCRIPTION
**Pull request by P0lip**

### CODE REVIEW

**Comment by billiegoose** [comment]
Are we gonna support rendering them too? Like, are we _actually_ gonna support Jira blocks officially or is this just an optimization?

**Comment by P0lip** [comment]
> Are we gonna support rendering them too? Like, are we actually gonna support Jira blocks officially or is this just an optimization?

@marbemac said no, so it's just an optimization.

**Comment by billiegoose** [comment]
I'm really uncomfortable with us hacking the Markdown parser to support other languages, when the syntax overlaps and can create something ambiguous. The example I'm analyzing right now is this:

```md
[block:code]
(https://github.com)

...

[/block]
(https://bitbucket.com)
```

That's valid Markdown for two URLs.

Studio renders it like this:
image

GitHub (with it's weird "newlines matter" flavor of Markdown) renders this:

[block:code]
(https://github.com)

...

[/block]
(https://bitbucket.com)

So this is a actually a breaking change to the parser, and will make it support a subset of the Markdown it previously could support. We're creating a weird edge case:

1. Links work UNLESS your link is on a line by itself and the text is "block:*" and the URL is on the next line, and you have a line "[/block]" later in the document.

The purist in me says if we keep adding little edge cases like this the parser will become really hard to reason about. But the pragmatist in me concedes the parser is probably already really hard to reason about, and I'm worrying about pee in the ocean. So 🤷‍♂ .

**Comment by P0lip** [comment]
It's only a plugin, so you can always get rid of it pretty easily - just a matter of removing `use` call.

Re
```
[block:code]
(https://github.com)
```
Yeah, this one is tricky, hm.

**Review by billiegoose — APPROVED** [review]
I think the benefit to our users outweighs the con of the edge case.

**Comment by marbemac** [comment]
I haven't looked under the hood yet, but all we really need is to just not crap out - ideally we don't treat jira blocks in a special way at all, they're just rendered like regular text. Is that what this does / is that possible?

**Comment by P0lip** [comment]
@wmhilton Ideally we expose an option in Studio.
Since it's a plugin, it'd be trivial to swap it out or in easily.

> I haven't looked under the hood yet, but all we really need is to just not crap out - ideally we don't treat jira blocks in a special way at all, they're just rendered like regular text. Is that what this does / is that possible?

well, it's just a special `jira` node with `text` property equals to the actual value placed inside of blocks.

**Comment by billiegoose** [comment]
> Ideally we expose an option in Studio.

nooooo. that is not ideal. Ideally studio has zero options. 😆 ideally no one ever tries to create a hyperlink in exactly that edge case.

>  ideally we don't treat jira blocks in a special way at all, they're just rendered like regular text. 

that's what this does. the "problem" is jira syntax overlaps with markdown syntax such that you can craft a document that's ambiguous. so rendering it like "regular text" would be a regression, since previously it rendered as a hyperlink. But I'm 99% certain no one will ever hit the edge case.

**Comment by P0lip** [comment]
Alright, I'm hitting the merge button then.

**Comment by marbemac** [comment]
> well, it's just a special jira node with text property equals to the actual value placed inside of blocks.

What's the underlying reason that it freezes with this document? Like what is that [code] or whatever block doing to cause this?

**Comment by P0lip** [comment]
> What's the underlying reason that it freezes with this document? Like what is that [code] or whatever block doing to cause this?

It's treated as paragraph, so it undergoes a more in-depth inline tokenization process, where single words are analyzed, so for instance the following document
```
[block:code]
**foo**
[/block]
```
is seen as

- linkReference
- strong
- linkReference

Does it make sense?

**Pull request merged**
